apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v3xzp27br-nodejs
  janus-idp.io/tekton: v3xzp27br-nodejs
  backstage.io/kubernetes-id: v3xzp27br-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v3xzp27br-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
